{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "timezone.fullname" . }}
  labels:
    {{- include "timezone.labels" . | nindent 4 }}
spec:
  defaultBackend:
    service:
      name: {{ include "timezone.fullname" . }}
      port:
        number: {{ .Values.containerPort }}
{{- end }}