apiVersion: v1
kind: Service
metadata:
  name: {{ include "timezone.fullname" . }}
  labels:
    {{- include "timezone.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    run: {{ include "timezone.fullname" . }}
  type: NodePort